var activities;
export default  activities =[
    {   title:"Beach punta cana",
        category: "fitness",
        img:[`${process.env.PUBLIC_URL}/images/img1.jpg`,`${process.env.PUBLIC_URL}/images/img2.jpg`,`${process.env.PUBLIC_URL}/images/img3.jpg`,`${process.env.PUBLIC_URL}/images/img4.jpg`],
        location:"Bishop avenue chicago",
        description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
        pricing:[{title:"basic",price:"32$",description:""}],
        expectation:"",
        city: "Chicago",
        views:43,
        cancellationPolicy:"",
        reviews: [{author:"john doe",description:"Nice experience",rating:1.2,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/pawandeep.jpg`}],
        openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
     },
     {  title:"Beach cancum",
        category: "fitness",
        img:[`${process.env.PUBLIC_URL}/images/img1.jpg`,`${process.env.PUBLIC_URL}/images/img2.jpg`,`${process.env.PUBLIC_URL}/images/img3.jpg`,`${process.env.PUBLIC_URL}/images/img4.jpg`],
        location:"964 school street, bercelona",
        description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
        pricing:[{title:"basic",price:"32$",description:""}],
        expectation:"",
        city: "Bercelona",
        views:43,
        cancellationPolicy:"",
        reviews: [{author:"john doe",description:"Nice experience",rating:3.3,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/pawandeep.jpg`}],
        openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
     },
     {  title:"Tom's resturant",
        category: "resturants",
        img:[`${process.env.PUBLIC_URL}/images/search.jpeg`,`${process.env.PUBLIC_URL}/images/sa.jpg`,`${process.env.PUBLIC_URL}/images/sightseeing.jpg`],
        location:"433 country street seville",
        description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
        pricing:[{title:"basic",price:"32$",description:""}],
        expectation:"",
        city: "seville",
        views:43,
        cancellationPolicy:"",
        reviews: [{author:"john doe",description:"Nice experience",rating:5,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/sonu.jpg`}],
        openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
     },
     {  title:"Hot spicy",
        category: "resturants",
        img:[`${process.env.PUBLIC_URL}/images/search.jpeg`,`${process.env.PUBLIC_URL}/images/sa.jpg`,`${process.env.PUBLIC_URL}/images/sightseeing.jpg`,`${process.env.PUBLIC_URL}/images/Manama.jpeg`],
        location:"1512 duncan avenue prague",
        description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
        pricing:[{title:"basic",price:"32$",description:""}],
        expectation:"",
        city: "prague",
        views:43,
        cancellationPolicy:"",
        reviews: [{author:"john doe",description:"Nice experience",rating:3.3,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/pawandeep.jpg`}],
        openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
     },
     {  title:"White field hotel",
     category: "hotels",
     img:[`${process.env.PUBLIC_URL}/images/search.jpeg`,`${process.env.PUBLIC_URL}/images/sa.jpg`,`${process.env.PUBLIC_URL}/images/sightseeing.jpg`,`${process.env.PUBLIC_URL}/images/Manama.jpeg`],
     location:"232 White field avenue monterrey",
     description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
     pricing:[{title:"basic",price:"32$",description:""}],
     expectation:"",
     city: "monterrey",
     views:43,
     cancellationPolicy:"",
     reviews: [{author:"john doe",description:"Nice experience",rating:3.3,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/pawandeep.jpg`}],
     openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
  },
  {  title:"Kwara hotel",
     category: "hotels",
     img:[`${process.env.PUBLIC_URL}/images/search.jpeg`,`${process.env.PUBLIC_URL}/images/sa.jpg`,`${process.env.PUBLIC_URL}/images/sightseeing.jpg`,`${process.env.PUBLIC_URL}/images/Manama.jpeg`],
     location:"432 G.R.A nigeria",
     description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
     pricing:[{title:"basic",price:"32$",description:""}],
     expectation:"",
     city: "nigeria",
     views:43,
     cancellationPolicy:"",
     reviews: [{author:"john doe",description:"Nice experience",rating:3.3,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/pawandeep.jpg`}],
     openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
  },
  {  title:"Kaystore",
     category: "shops",
     img:[`${process.env.PUBLIC_URL}/images/search.jpeg`,`${process.env.PUBLIC_URL}/images/sa.jpg`,`${process.env.PUBLIC_URL}/images/sightseeing.jpg`,`${process.env.PUBLIC_URL}/images/Manama.jpeg`],
     location:"322 kaystore avenue monterrey",
     description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
     pricing:[{title:"basic",price:"32$",description:""}],
     expectation:"",
     city: "monterrey",
     views:43,
     cancellationPolicy:"",
     reviews: [{author:"john doe",description:"Nice experience",rating:3.3,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/pawandeep.jpg`}],
     openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
  },
  {  title:"Toyyibah's collection",
     category: "shops",
     img:[`${process.env.PUBLIC_URL}/images/search.jpeg`,`${process.env.PUBLIC_URL}/images/sa.jpg`,`${process.env.PUBLIC_URL}/images/sightseeing.jpg`,`${process.env.PUBLIC_URL}/images/Manama.jpeg`],
     location:"1512 prince ali street dubai",
     description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
     pricing:[{title:"basic",price:"32$",description:""}],
     expectation:"",
     city: "dubai",
     views:43,
     cancellationPolicy:"",
     reviews: [{author:"john doe",description:"Nice experience",rating:5,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/pawandeep.jpg`}],
     openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
  },
  {  title:"Muscle builders",
     category: "fitness",
     img:[`${process.env.PUBLIC_URL}/images/search.jpeg`,`${process.env.PUBLIC_URL}/images/sa.jpg`,`${process.env.PUBLIC_URL}/images/sightseeing.jpg`,`${process.env.PUBLIC_URL}/images/Manama.jpeg`],
     location:"1512 duncan avenue new york",
     description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
     pricing:[{title:"basic",price:"32$",description:""}],
     expectation:"",
     city: "new york",
     views:43,
     cancellationPolicy:"",
     reviews: [{author:"john doe",description:"Nice experience",rating:3.3,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/pawandeep.jpg`}],
     openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
  },
  {  title:"The Gymnast",
     category: "fitness",
     img:[`${process.env.PUBLIC_URL}/images/search.jpeg`,`${process.env.PUBLIC_URL}/images/sa.jpg`,`${process.env.PUBLIC_URL}/images/sightseeing.jpg`,`${process.env.PUBLIC_URL}/images/Manama.jpeg`],
     location:"12 pablo street cartegena",
     description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
     pricing:[{title:"basic",price:"32$",description:""}],
     expectation:"",
     city: "Cartegena",
     views:43,
     cancellationPolicy:"",
     reviews: [{author:"john doe",description:"Nice experience",rating:4.3,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/pawandeep.jpg`}],
     openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
  },
  {  title:"The great circle",
  category: "events",
  img:[`${process.env.PUBLIC_URL}/images/search.jpeg`,`${process.env.PUBLIC_URL}/images/sa.jpg`,`${process.env.PUBLIC_URL}/images/sightseeing.jpg`,`${process.env.PUBLIC_URL}/images/Manama.jpeg`],
  location:"1512 white house usa",
  description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
  pricing:[{title:"basic",price:"32$",description:""}],
  expectation:"",
  city: "usa",
  views:43,
  cancellationPolicy:"",
  reviews: [{author:"john doe",description:"Nice experience",rating:2.3,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/pawandeep.jpg`}],
  openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
},
{  title:"The headies award",
  category: "events",
  img:[`${process.env.PUBLIC_URL}/images/search.jpeg`,`${process.env.PUBLIC_URL}/images/sa.jpg`,`${process.env.PUBLIC_URL}/images/sightseeing.jpg`,`${process.env.PUBLIC_URL}/images/Manama.jpeg`],
  location:"1512 duncan avenue canada",
  description: "Cheddar cheese, lettuce, tomato, onion, dill pickles Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque .",
  pricing:[{title:"basic",price:"32$",description:""}],
  expectation:"",
  city: "canada",
  views:43,
  cancellationPolicy:"",
  reviews: [{author:"john doe",description:"Nice experience",rating:4.3,img:[],helpful:32,dp:`${process.env.PUBLIC_URL}/images/pawandeep.jpg`}],
  openingHours:[{day:"monday",start:"8am",end:"5pm"},{day:"tuesday",start:"8am",end:"5pm"},{day:"wednesday",start:"8am",end:"5pm"},{day:"thursday",start:"8am",end:"5pm"},{day:"monday",start:"8am",end:"5pm"},{day:"friday",start:"8am",end:"5pm"}]
},
]

export var categories =[
  {title:"shops",img:`${process.env.PUBLIC_URL}/images/sightseeing.jpg`},
  {title:"hotels",img:`${process.env.PUBLIC_URL}/images/sa.jpg`},
  {title:"restaurants",img:`${process.env.PUBLIC_URL}/images/search.jpeg`},
  {title:"events",img:`${process.env.PUBLIC_URL}/images/sightseeing.jpg`},
  {title:"fitness",img:`${process.env.PUBLIC_URL}/images/sa.jpg`},
]